name: ai-course
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - scikit-learn
  - plotly
  - numpy
  - ucimlrepo
  - mlflow
  - streamlit
  - ipykernel
  - nbformat>=5.7
  - nbconvert
  - feature_engine
  - shap
